Update copy right, remove broucher, case study and fix contact icons
sayam56/NerdySite pull request #76
Opened 2024-06-16 02:23 UTC by mohammadalihera

2024-06-16 02:56 UTC, sayam56 requested changes
Please check the comments and update/ provide feedback as needed

2024-06-16 02:56 UTC, sayam56 commented on account.html
What is this file and what are the changes on it?

2024-06-16 02:56 UTC, sayam56 commented on application_case_study.html
Why do we have changes in case study too?

2024-06-16 02:56 UTC, sayam56 commented on faq.html
> +            <div class="copyright">Copyright © 2024NerdEvolution. All Rights Reserved.</div>
Space Missing

2024-06-16 02:56 UTC, sayam56 commented on brand_identity.html
> +            <div class="copyright">Copyright © 2024NerdEvolution. All Rights Reserved.</div>
Space missing in all of them

2024-06-16 02:56 UTC, sayam56 commented on functional-resume.html
> +            <div class="copyright">Copyright © 2024NerdEvolution. All Rights Reserved.</div>
Please fix this spacing issue in all of them

2024-06-16 02:56 UTC, sayam56 commented on not-found.html
Why changes in here?

2024-06-16 02:56 UTC, sayam56 commented on ui_ux_detail.html
Are these new contents from the team? I am a bit confused

2024-06-28 14:33 UTC, mohammadalihera commented on faq.html
> +            <div class="copyright">Copyright © 2024NerdEvolution. All Rights Reserved.</div>
Fix review

2024-06-28 14:36 UTC, mohammadalihera commented on account.html
Here I change only in the copy right section

2024-06-28 14:37 UTC, mohammadalihera commented on application_case_study.html
I have changed the copy right by searching it and replacing it. so it became change everywhere

2024-06-28 14:42 UTC, mohammadalihera commented on functional-resume.html
> +            <div class="copyright">Copyright © 2024NerdEvolution. All Rights Reserved.</div>
Fixed this spacing issue in all of the pages

2024-06-28 15:59 UTC, sayam56 requested changes

2024-06-28 15:59 UTC, sayam56 commented on account.html
![image](https://github.com/sayam56/NerdySite/assets/58643389/d3f46ebe-40e8-419e-a3f4-e3c88e62b4f4)
But look at the diffs, there's so many changes. Did you pull from master before making the changes and submitting the PR?

2024-06-28 15:59 UTC, sayam56 commented on application_case_study.html
![image](https://github.com/sayam56/NerdySite/assets/58643389/2153306d-74b6-4f28-b3a4-bdd647a20c19)
Again, I see a lot of changes other than just the copyright information. Did you make sure to pull from main/'master before submitting the PR?

2024-06-28 15:59 UTC, sayam56 commented on not-found.html
![image](https://github.com/sayam56/NerdySite/assets/58643389/45373816-b7c3-405d-a5e8-23af0ea031c3)
I see a lot more than just copyright changes. Please let me know what these are.

2024-06-28 15:59 UTC, sayam56 commented on ui_ux_detail.html
@mohammadalihera Please justify this as well. Thanks

2024-06-28 16:14 UTC, mohammadalihera commented on ui_ux_detail.html
Yes, Ui Ux is new contents, but I need the images and content for this screen

2024-06-28 16:18 UTC, sayam56 commented on ui_ux_detail.html
If this screen is not ready to be public yet, please make sure you remove the links to this page from the UI.

2024-06-28 16:22 UTC, mohammadalihera commented on account.html
![image](https://github.com/sayam56/NerdySite/assets/67761216/04d73d27-3301-4eab-9a8c-fa5eb5d95eea)
Yes I took pull. and in the git hub I am not seeing these chnages, is your diff upto date?

2024-07-07 19:59 UTC, merged